#server:
#  port: 8082
#数据库连接 mysql
spring:
  profiles:
    active: dev

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mybatis/*.xml
  # 实体类映射
  #type-aliases-package:
logging:
  level:
    com:
      bi:
        mapper: debug

