server:
  port: 8082
#数据库连接 mysql
spring:
  datasource:
    url: jdbc:mysql://124.223.68.253:3306/bi?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: bi2022
    driver-class-name: com.mysql.cj.jdbc.Driver

    clickHouse:
      url: jdbc:clickhouse://124.223.68.253:8123/default
      username: default
      password: bi2022
      driver-class-name: cc.blynk.clickhouse.ClickHouseDriver



mybatis:
  #mapper配置文件
  mapper-locations: classpath:mybatis/*.xml
  # 实体类映射
  #type-aliases-package:
logging:
  level:
    com:
      bi:
        mapper: debug
