server:
  port: 8082
#数据库连接 mysql
spring:
  datasource:
    mysql:
      url: jdbc:mysql://124.223.68.253:3306/bi?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
      password: bi2022
      driver-class-name: com.mysql.cj.jdbc.Driver
    clickHouse:
      url: jdbc:clickhouse://124.223.68.253:8123/default
      username: default
      password: bi2022
      driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
#      driver-class-name: cc.blynk.clickhouse.ClickHouseDriver

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true
  # 实体类映射
  #type-aliases-package:
logging:
  level:
    com:
      bi:
        mapper: debug

management:
  # 端点信息接口使用的端口，为了和主系统接口使用的端口进行分离
  server:
    port: 8090
    servlet:
      context-path: /sys
  # 端点健康情况，默认值"never"，设置为"always"可以显示硬盘使用情况和线程情况
  endpoint:
    health:
      show-details: always
  # 设置端点暴露的哪些内容，默认["health","info"]，设置"*"代表暴露所有可访问的端点
  endpoints:
    web:
      exposure:
        include: '*'
